#include <iostream>
#include "grid.hpp"
#include "wave.hpp"
#include "globals.hpp"
#include <fstream>
#include <filesystem>
#include <cmath>
#include <cstdlib>
#include <stdexcept>
#include <string>

namespace grid{

void pot_h2p(GridData &gridd)
{
	constexpr double k1 = 1.0;
	constexpr double k2 =  1.0;
	constexpr double kappa =  1.0;
	constexpr double V0 = 0.0; 

	for (int i = 0; i < ni; ++i)
	{
	for (int j = 0; j < nj; ++j)
		{
			double xp = - kappa * gridd.yg[j] * gridd.yg[j];
			double h1 = gridd.xg[i] - 0.5 * gridd.yg[j];
			double h2 = gridd.xg[i] + 0.5 * gridd.yg[j];

			gridd.v[i][j][0][0] = V0 * std::exp(xp) + 0.5 * k1 * h1 * h1 + 0.5 * k2 * h2 * h2;
			
		}
	}
}	

void load_surface_file(const std::string &path, GridData &gridd, int n1, int n2)
{
	std::ifstream infile(path);
	if (!infile) {
		throw std::runtime_error("Unable to open NaFH potential file: " + path);
	}

	double x = 0.0;
	double y = 0.0;
	double value = 0.0;
	int points_read = 0;

	for (int j = 0; j < nj; ++j) {
		for (int i = 0; i < ni; ++i) {
			if (!(infile >> x >> y >> value)) {
				throw std::runtime_error(
					"Unexpected end of NaFH potential file: " + path);
			}

		gridd.v[i][j][n1][n2] = value;
			++points_read;
		}
	}

	if (points_read != ni * nj) {
		throw std::runtime_error(
			"Unexpected number of grid points in " + path + ": read " +
			std::to_string(points_read) + ", expected " + std::to_string(ni * nj));
	}

	if (infile >> x >> y >> value) {
		throw std::runtime_error("NaFH potential file has extra grid points: " + path);
	}
}

void write_nafh_input_file(const std::string &path)
{
	std::ofstream outfile(path);
	if (!outfile) {
		throw std::runtime_error("Unable to write NaFH input file: " + path);
	}

	outfile << grid::xmin << "d0," << grid::xmax << "d0 \\rNaH_min,rNaH_max\n"
	        << grid::ymin << "d0," << grid::ymax << "d0 \\rF_min,rF_max\n"
	        << ni << " \\nx\n"
	        << nj << " \\ny\n";
}

void run_nafh_driver(const std::string &surface_dir)
{
	const std::filesystem::path original_dir = std::filesystem::current_path();
	const std::filesystem::path work_dir(surface_dir);
	const std::filesystem::path executable = work_dir / "nafh2d.x";

	if (!std::filesystem::exists(executable)) {
		throw std::runtime_error("NaFH driver executable not found: " + executable.string());
	}

	std::filesystem::current_path(work_dir);
	const int status = std::system("./nafh2d.x");
	std::filesystem::current_path(original_dir);

	if (status != 0) {
		throw std::runtime_error("NaFH driver failed with exit code " + std::to_string(status));
	}
}

	void pot_NaFH(GridData &gridd)
	// Load the precomputed NaFH diabatic surfaces generated by the Fortran driver.
	{
		const std::string surface_dir = "/home/julianps/Codes/NaFH2D";
		const std::string input_file = surface_dir + "/input";

		write_nafh_input_file(input_file);
		std::cout << "Writing NaFH driver input to " << input_file << std::endl;
		run_nafh_driver(surface_dir);

		for (int i = 0; i < ni; ++i) {
			for (int j = 0; j < nj; ++j) {
				for (int n1 = 0; n1 < ns; ++n1) {
					for (int n2 = 0; n2 < ns; ++n2) {
						gridd.v[i][j][n1][n2] = 0.0;
					}
				}
			}
		}

		load_surface_file(surface_dir + "/U11.dat", gridd, 0, 0);
		load_surface_file(surface_dir + "/U12.dat", gridd, 0, 1);
		load_surface_file(surface_dir + "/U22.dat", gridd, 1, 1);

		for (int i = 0; i < ni; ++i) {
			for (int j = 0; j < nj; ++j) {
				gridd.v[i][j][1][0] = gridd.v[i][j][0][1];
			}
		}
	}


	void pot_doublewell(GridData &gridd)
	{
		constexpr double eta = 1/1.3544;
		constexpr double b =  1.0;
		constexpr double c =  1.0;
		constexpr double d = 1.0; //Linear Coupling

		for (int i = 0; i < ni; ++i)
		{
		for (int j = 0; j < nj; ++j)
			{
			
			gridd.v[i][j][0][0] = 0.0625 * eta * (gridd.xg[i]*gridd.xg[i]) * (gridd.xg[i]*gridd.xg[i]) - 0.5 * b * (gridd.xg[i]*gridd.xg[i]) + 0.5 * c * gridd.yg[j]*gridd.yg[j] + 0.5 * d * gridd.xg[i]*gridd.yg[j]; //Ground PES Linear Coupling
		//	gridd.v[i][j][1][1] = 0.0625 * eta * (gridd.xg[i]*gridd.xg[i]) * (gridd.xg[i]*gridd.xg[i]) - 0.5 * b * (gridd.xg[i]*gridd.xg[i]) + 0.5 * c * gridd.yg[j]*gridd.yg[j] + 0.5 * d * gridd.xg[i]*gridd.yg[j]; //Excited PES Linear Coupling
		//	gridd.v[i][j][1][0] = 0; //Coupling
		//	gridd.v[i][j][0][1] = gridd.v[i][j][1][0]; //Symmetric Coupling

			
			
			}
		}
	   }

	void pot_Ferretti(GridData &gridd)
	{
		//Model parameters
		constexpr double Kx = 0.02;
		constexpr double Ky = 0.1;
		constexpr double X1 = 4.0;
		constexpr double X2 = 3.0;
		constexpr double X3 = 3.0;
		constexpr double alpha = 3.0;
		constexpr double beta = 1.5;
		constexpr double gamma = 0.01;
		constexpr double Delta = 0.01; 

		for (int i = 0; i < ni; ++i)
		{
		for (int j = 0; j < nj; ++j)
			{
			
			gridd.v[i][j][0][0] = 0.5 * Kx * (gridd.xg[i]-X1)*(gridd.xg[i]-X1) + 0.5 * Ky * gridd.yg[j]*gridd.yg[j]; //Ground PES
			gridd.v[i][j][1][1] = 0.5 * Kx * (gridd.xg[i]-X2)*(gridd.xg[i]-X2) + 0.5 * Ky * gridd.yg[j]*gridd.yg[j] + Delta; //Excited PES
			gridd.v[i][j][1][0] = gamma * gridd.yg[j] * exp(-alpha * (gridd.xg[i]-X3)*(gridd.xg[i]-X3)  - beta * gridd.yg[j]*gridd.yg[j]); //Coupling
			gridd.v[i][j][0][1] = gridd.v[i][j][1][0]; //Symmetric Coupling



			}

		}
	   }

	void pot_LandauSomb(GridData &gridd)
          {
		//constexpr double va = 0.17;
		constexpr double re = 1.4;

		for (int i = 0; i < ni; ++i)
		{
		for (int j = 0; j < nj; ++j)
    		{
			double r = std::sqrt(gridd.xg[i]*gridd.xg[i]+gridd.yg[j]*gridd.yg[j]);
			
			for (int n1 = 0; n1 < ns; ++n1)
			{
			for (int n2 = 0; n2 < ns; ++n2)
			{
				if (n1 == n2)
				 { gridd.v[i][j][n1][n2] = 0.5 * (r-re) * (r-re); //single PES
				 }
				else
				 { gridd.v[i][j][n1][n2] = 0.0; // single uncoupled PES
				 }
			}
			}

    		}
		}
	   }
	   void pick_pot(int pot_name, GridData &gridd)
	   {
		switch (pot_name)
		{
		case 0:
			pot_LandauSomb(gridd);
			std::cout << "Using Landau-Sombrero potential\n";
			break;
		case 1:
			pot_Ferretti(gridd);
			std::cout << "Using Ferretti potential\n";
			break;
		case 2:
			pot_doublewell(gridd);
			std::cout << "Using Double Well potential\n";
			break;
		case 3:
			pot_NaFH(gridd);
			std::cout << "Using NaFH potential\n";
			break;
		case 4:
			pot_h2p(gridd);
			std::cout << "Using Model H2+ potential\n";
			break;
		default:
			std::cerr << "Invalid potential name: " << pot_name << "\n";
			break;
		}
    	}
}
